Logo entièrement clickable + photos de slide centrées
lescadev/benroc pull request #23
Opened 2019-05-03 13:32 UTC by Quentin-Se

Logo entièrement clickable + photos de slide centrées

2019-05-03 13:34 UTC, VicomteA approved these changes

2019-05-03 13:38 UTC, russian-boy approved these changes

2019-05-03 13:41 UTC, PierreMASSALOUX approved these changes

2019-05-03 13:43 UTC, nicolasvauche commented
please indent your code
<img width="449" alt="Capture d’écran 2019-05-03 à 15 42 47" src="https://user-images.githubusercontent.com/16921038/57141337-3f02bf00-6dba-11e9-84c5-734d1a9a6544.png">

2019-05-03 13:44 UTC, nicolasvauche requested changes
please indent your code
<img width="449" alt="Capture d’écran 2019-05-03 à 15 42 47" src="https://user-images.githubusercontent.com/16921038/57141371-5346bc00-6dba-11e9-94d4-f8d9d907eea9.png">

2019-05-03 14:05 UTC, milleka approved these changes

2019-05-03 14:21 UTC, PierreMASSALOUX approved these changes

2019-05-06 07:55 UTC, nicolasvauche approved these changes

2019-05-06 07:56 UTC, merged